IMAGE_NAME = "bento/ubuntu-18.04"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    if Vagrant.has_plugin?("vagrant-vbguest")
	    config.vbguest.auto_update = false  
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provider :virtualbox do |vb|
            vb.gui  = false
            vb.name = "k8s-master"
        end
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
        end
    end

    (1..N).each do |i|
        config.vm.define "k8s-worker-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "k8s-worker-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.gui  = false
                vb.name = "k8s-worker-#{i}"
            end
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
            end
        end
    end
end
