# https://kind.sigs.k8s.io/docs/user/quick-start/#configuring-your-kind-cluster 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cdaas
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
- role: worker
- role: worker
