apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "5.3.0" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.1.0/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: local.vodafoneziggo.com # Provide a real base domain for GitLab. "gitlab." and "registry." will be exposed as subdomains.
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: faraz.foroozan@vodafoneziggo.com
